on:
  push:
    branches:
      - master

name: release-24.0.1

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Debug
        run: |
          pwd
          ls -al

      - name: Update version in config.gradle
        run: |
          sed -ie 's/versionName .*/versionName 24.0.1/' app/config.gradle
          git add app/config.gradle
          git commit -m "Automated commit by GitHub Actions to update version name"
          git push --set-upstream origin release/release-24.0.1
